export const PERMISSION_EVALUATOR = Symbol('PERMISSION_EVALUATOR');
export const ENTITLEMENT_EVALUATOR = Symbol('ENTITLEMENT_EVALUATOR');
export const AUDIT_RECORDER = Symbol('AUDIT_RECORDER');
export const OUTBOX_PUBLISHER = Symbol('OUTBOX_PUBLISHER');
export const TRANSACTION_RUNNER = Symbol('TRANSACTION_RUNNER');
