export enum ContentEditorCapability {
  RICH_TEXT = 'RICH_TEXT',
  BLOCK_TREE = 'BLOCK_TREE',
  EMBEDS = 'EMBEDS',
  FILES = 'FILES',
  AI_ASSISTED_DRAFTING = 'AI_ASSISTED_DRAFTING',
  ASSESSMENT_BLOCKS_RESERVED = 'ASSESSMENT_BLOCKS_RESERVED',
}
