export enum ContentDocumentPurpose {
  COURSE_CONTENT = 'COURSE_CONTENT',
  LESSON_CONTENT = 'LESSON_CONTENT',
  ASSESSMENT_CONTENT_RESERVED = 'ASSESSMENT_CONTENT_RESERVED',
  QUESTION_CONTENT_RESERVED = 'QUESTION_CONTENT_RESERVED',
  GENERAL_PAGE = 'GENERAL_PAGE',
}
